import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web3 Growth, Powered by Insight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <head>
        <meta name="color-scheme" content="light" />
        <meta name="theme-color" content="#ffffff" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/riverstone-logo.png"
        />
        {/* --- Social preview --- */}
        <meta property="og:title" content="Web3 Growth, Powered by Insight" />
        <meta property="og:description" content="Capital, Strategy, and Narrative" />
        <meta property="og:image" content="https://riverstone.one/riverstone-logo.png" />
        <meta property="og:url" content="https://riverstone.one" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Riverstone" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Web3 Growth, Powered by Insight" />
        <meta name="twitter:description" content="Capital, Strategy, and Narrative" />
        <meta name="twitter:image" content="https://riverstone.one/riverstone-logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
        style={{ minHeight: '100vh' }}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}