import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen`}
        style={{ minHeight: '100vh' }}
      >
        <div className="flex justify-center items-start min-h-screen w-full">
          <div className="border border-foreground rounded-2xl p-2 m-2 min-h-screen w-full max-w-6xl bg-white/95 shadow-2xl overflow-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
